version: '2.1'
services:
    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Sequential
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/db/airflow.db
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./db:/usr/local/airflow/db
            - ./modules:/usr/local/airflow/modules
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    scheduler:
        image: puckel/docker-airflow:1.10.9
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Sequential
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/db/airflow.db
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./db:/usr/local/airflow/db
        command: scheduler
